name: Build

on:
  pull_request:
  push:
    branches: ['**']

jobs:
  nextflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: MillironX/setup-nextflow@v1
      # On validates flow:
      #   Confirms workflow is valid
      #   Confirms all containers are available
      - run: |
          nextflow run main.nf -stub --check test/example.csv
          # expect lines to pass
          ls -l results
          cat results/md5_results.txt
          grep -c '\t0$' results/
      - run: |
          nextflow run main.nf --check test/example.csv
          # expect both pass and fail
          grep -c '\t0$' results/md5_results.txt
          grep -c '\t1$' results/md5_results.txt
